package PkAdmin;

import PkOrders.OrderDetails;
import PkOrders.DisplayOrderRecords;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.Color;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTextField;

public class ManageOrderRecords extends javax.swing.JFrame {

    String status;
    int getRecord;
    String fees;
    String greutate;
    int rate=0;
    String feedback="";
    public ManageOrderRecords() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SenderID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        StaffIDb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        orderid = new javax.swing.JTextField();
        sendername = new javax.swing.JTextField();
        receiverName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        receiveraddress = new javax.swing.JTextField();
        backb = new javax.swing.JButton();
        payments = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        receiverphone = new javax.swing.JTextField();
        addb = new javax.swing.JButton();
        viewb = new javax.swing.JButton();
        searchb = new javax.swing.JButton();
        updateb = new javax.swing.JButton();
        deleteb = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        confrimb = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        SenderID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenderIDActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Delivery StaffID");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Customer ID");

        StaffIDb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffIDbActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Order ID");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Customer Name");

        orderid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderidActionPerformed(evt);
            }
        });

        sendername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendernameActionPerformed(evt);
            }
        });

        receiverName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiverNameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Receiver Name");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Receiver Address");

        receiveraddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiveraddressActionPerformed(evt);
            }
        });

        backb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backb.setText("Back");
        backb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Payment");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Receiver Phone");

        addb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addb.setText("Create");
        addb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbActionPerformed(evt);
            }
        });

        viewb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        viewb.setText("View");
        viewb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbActionPerformed(evt);
            }
        });

        searchb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        searchb.setText("Search");
        searchb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbActionPerformed(evt);
            }
        });

        updateb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        updateb.setText("Update");
        updateb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebActionPerformed(evt);
            }
        });

        deleteb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        deleteb.setText("Delete");
        deleteb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Receiver Information");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("Sender Information");

        confrimb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        confrimb.setText("Confirm Update");
        confrimb.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                confrimbStateChanged(evt);
            }
        });
        confrimb.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                confrimbComponentHidden(evt);
            }
        });
        confrimb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confrimbActionPerformed(evt);
            }
        });
        
        JLabel lblWeight = new JLabel();
        lblWeight.setText("Weight");
        lblWeight.setFont(new Font("Times New Roman", Font.BOLD, 12));
        
        weight = new JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(36)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 89, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jLabel8, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 89, GroupLayout.PREFERRED_SIZE))
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addComponent(payments, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE)
        									.addGap(0, 292, Short.MAX_VALUE))
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        										.addComponent(orderid, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
        										.addComponent(StaffIDb, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE))
        									.addPreferredGap(ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
        									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        										.addGroup(jPanel1Layout.createSequentialGroup()
        											.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 89, GroupLayout.PREFERRED_SIZE)
        											.addPreferredGap(ComponentPlacement.UNRELATED)
        											.addComponent(SenderID, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE))
        										.addComponent(jLabel11)))
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addPreferredGap(ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
        									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        										.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        											.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 89, GroupLayout.PREFERRED_SIZE)
        											.addPreferredGap(ComponentPlacement.UNRELATED))
        										.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        											.addComponent(confrimb)
        											.addGap(30))
        										.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        											.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        												.addComponent(weight, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE)
        												.addComponent(lblWeight, GroupLayout.PREFERRED_SIZE, 89, GroupLayout.PREFERRED_SIZE))
        											.addGap(42)))
        									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        										.addComponent(sendername, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE)
        										.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        											.addComponent(updateb, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE)
        											.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        												.addComponent(deleteb, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        												.addComponent(searchb, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        												.addComponent(viewb, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        												.addComponent(addb, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))))))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 89, GroupLayout.PREFERRED_SIZE)
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addComponent(receiverphone, GroupLayout.PREFERRED_SIZE, 113, GroupLayout.PREFERRED_SIZE))
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        										.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 89, GroupLayout.PREFERRED_SIZE)
        										.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        											.addComponent(jLabel7, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        											.addComponent(jLabel4, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        										.addComponent(receiverName, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE)
        										.addComponent(receiveraddress, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE))))
        							.addGap(0, 290, Short.MAX_VALUE)))
        					.addGap(26))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel10)
        						.addComponent(backb))
        					.addContainerGap(411, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(24)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(StaffIDb, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel2, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        						.addComponent(orderid, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jLabel11)
        					.addGap(18)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(SenderID, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
        					.addGap(15)))
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(48)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(receiverName, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        						.addComponent(addb, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        							.addComponent(receiveraddress, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        							.addComponent(viewb, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
        						.addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel8, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(payments, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(searchb, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
        						.addComponent(receiverphone, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
        						.addComponent(deleteb, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(jLabel10)
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        							.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        							.addComponent(sendername, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)))
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        							.addGap(123))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(lblWeight, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(weight, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        							.addGap(88)))))
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(updateb, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
        				.addComponent(confrimb))
        			.addPreferredGap(ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
        			.addComponent(backb)
        			.addGap(33))
        );
        jPanel1.setLayout(jPanel1Layout);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new Color(153, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Order Records");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StaffIDbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffIDbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StaffIDbActionPerformed

    private void orderidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderidActionPerformed

    private void sendernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendernameActionPerformed

    private void receiverNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiverNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiverNameActionPerformed

    private void receiveraddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveraddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiveraddressActionPerformed

    private void addbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbActionPerformed
        // TODO add your handling code here:
        if (receiverName.getText().equals("")||orderid.getText().equals("")||payments.getText().equals("")||
        StaffIDb.getText().equals("")||receiveraddress.getText().equals("")
                ||SenderID.getText().equals("")||sendername.getText().equals("")){
        JOptionPane.showMessageDialog(null, 
                "Please fill in all required fields", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
        else{
            OrderDetails st = new OrderDetails();
            if (st.search(orderid.getText())){
                JOptionPane.showMessageDialog(null, 
                        "This ID already exist", "Error Message", JOptionPane.ERROR_MESSAGE);      
            }
            else{
                AdminManagement af = new AdminManagement();
                fees = payments.getText();
                greutate = weight.getText();
                status = "Undelivered";
                try {
                    af.AddOrder(orderid.getText(),sendername.getText(), receiverName.getText(),
                            SenderID.getText(),StaffIDb.getText(), receiverphone.getText(), 
                             receiveraddress.getText(), greutate, feedback, status,fees, rate);
                    ManageOrderRecords get = new ManageOrderRecords();
                    this.dispose();
                    get.setVisible(true);
                    get.setLocationRelativeTo(null);
                } catch (IOException ex) {
                    Logger.getLogger(ManageOrderRecords.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
        
    }//GEN-LAST:event_addbActionPerformed

    private void updatebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebActionPerformed
        // TODO add your handling code here:
       
        //view order info
        String SID = JOptionPane.showInputDialog("Enter the order ID: ");
        if (SID.isEmpty()){
          JOptionPane.showMessageDialog(null, "Empty filed ", "Error Message", JOptionPane.ERROR_MESSAGE);    
        }
        else{
            AdminManagement st = new AdminManagement();
            getRecord = st.searchOrder(SID);
            if (getRecord == -1){
                 JOptionPane.showMessageDialog(null, "The order ID dose not exist", "Error Message", JOptionPane.ERROR_MESSAGE);      
            }
            else {
                  StaffIDb.setText(OrderDetails.getOrderlist().get(getRecord).getStaffID());
                  orderid.setText(OrderDetails.getOrderlist().get(getRecord).getOrderID());
                  SenderID.setText(OrderDetails.getOrderlist().get(getRecord).getCustomerID());
                  sendername.setText(OrderDetails.getOrderlist().get(getRecord).getCustomerName());
                  receiverName.setText(OrderDetails.getOrderlist().get(getRecord).getReceiverName());
                  receiveraddress.setText(OrderDetails.getOrderlist().get(getRecord).getReceiverAddress());
                  receiverphone.setText(OrderDetails.getOrderlist().get(getRecord).getReceiverPhone());
                  weight.setText(OrderDetails.getOrderlist().get(getRecord).getWeight()+"");
                  payments.setText(OrderDetails.getOrderlist().get(getRecord).getPayment()+"");
                 orderid.setEnabled(false);
                 StaffIDb.setEnabled(true);
                 receiveraddress.setEnabled(true);
                 receiverName.setEnabled(true);
                 SenderID.setEnabled(true);
                 sendername.setEnabled(true);
                 receiverphone.setEnabled(true);
                 weight.setEnabled(true);
                 payments.setEnabled(true);
                 confrimb.setEnabled(true);

                }
        }
       
        
    }//GEN-LAST:event_updatebActionPerformed

    private void deletebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebActionPerformed
        // TODO add your handling code here:
       
        String oID = JOptionPane.showInputDialog("Enter the order ID: ");
        if (oID.isEmpty()){
          JOptionPane.showMessageDialog(null, "Empty filed ", "Error Message", JOptionPane.ERROR_MESSAGE);    
        }
        else{
            AdminManagement st = new AdminManagement();
            int indexto = st.searchOrder(oID);
            if (indexto == -1){
                 JOptionPane.showMessageDialog(null, "The order ID dose not exist", "Error Message", JOptionPane.ERROR_MESSAGE);      
            }
            else {
                 AdminManagement af = new AdminManagement();
                try {
                    af.DeleteOrder(indexto);
                    ManageOrderRecords get = new ManageOrderRecords();
                    this.dispose();
                    get.setVisible(true);
                    get.setLocationRelativeTo(null);
                } catch (IOException ex) {
                    Logger.getLogger(ManageOrderRecords.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
    }//GEN-LAST:event_deletebActionPerformed

    private void searchbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbActionPerformed
        // TODO add your handling code here:
        
        String SID = JOptionPane.showInputDialog("Enter the order ID: ");
        if (SID.isEmpty()){
          JOptionPane.showMessageDialog(null, "Empty filed ", "Error Message", JOptionPane.ERROR_MESSAGE);    
        }
        else{
            AdminManagement st = new AdminManagement();
            int getRecord = st.searchOrder(SID);
            if (getRecord == -1){
                 JOptionPane.showMessageDialog(null, "The order ID dose not exist", "Error Message", JOptionPane.ERROR_MESSAGE);      
            }
            else {
                  StaffIDb.setText(OrderDetails.getOrderlist().get(getRecord).getStaffID());
                  orderid.setText(OrderDetails.getOrderlist().get(getRecord).getOrderID());
                  SenderID.setText(OrderDetails.getOrderlist().get(getRecord).getCustomerID());
                  sendername.setText(OrderDetails.getOrderlist().get(getRecord).getCustomerName());
                  receiverName.setText(OrderDetails.getOrderlist().get(getRecord).getReceiverName());
                  receiveraddress.setText(OrderDetails.getOrderlist().get(getRecord).getReceiverAddress());
                  receiverphone.setText(OrderDetails.getOrderlist().get(getRecord).getReceiverPhone());
                  weight.setText(OrderDetails.getOrderlist().get(getRecord).getWeight()+"");
                  payments.setText(OrderDetails.getOrderlist().get(getRecord).getPayment()+"");
                 orderid.setEnabled(false);
                 StaffIDb.setEnabled(false);
                 receiveraddress.setEnabled(false);
                 receiverName.setEnabled(false);
                 SenderID.setEnabled(false);
                 sendername.setEnabled(false);
                 receiverphone.setEnabled(false);
                 weight.setEnabled(false);
                 payments.setEnabled(false);

                }
        }
        
        
    }//GEN-LAST:event_searchbActionPerformed

    private void viewbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbActionPerformed
        // TODO add your handling code here:
        DisplayOrderRecords s = new DisplayOrderRecords();
        this.dispose();
        s.setLocationRelativeTo(null);
        s.setVisible(true);
    }//GEN-LAST:event_viewbActionPerformed

    private void SenderIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenderIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenderIDActionPerformed

    private void backbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        AdminPanel s = new AdminPanel();
        this.dispose();
        s.setLocationRelativeTo(null);
        s.setVisible(true);
    }//GEN-LAST:event_backbActionPerformed

    private void confrimbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confrimbActionPerformed
        // TODO add your handling code here:
         //validate
        if (receiverName.getText().equals("")||orderid.getText().equals("")
                 ||payments.getText().equals("")||
        StaffIDb.getText().equals("")||receiveraddress.getText().equals("")
                ||SenderID.getText().equals("")||sendername.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill in the new details first", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
        else{
            AdminManagement af = new AdminManagement();
                    fees = payments.getText();
                    status = OrderDetails.getOrderlist().get(getRecord).getStatus();
                    rate= OrderDetails.getOrderlist().get(getRecord).getRate();
                    feedback = OrderDetails.getOrderlist().get(getRecord).getFeedback();
                    greutate = weight.getText();

                    try {
                        af.editOrder(getRecord, orderid.getText(),sendername.getText(), receiverName.getText(),
                                SenderID.getText(),StaffIDb.getText(), receiverphone.getText(), 
                                 receiveraddress.getText(), greutate, feedback, status,fees, rate);
                        ManageOrderRecords get = new ManageOrderRecords();
                        this.dispose();
                        get.setVisible(true);
                        get.setLocationRelativeTo(null);
                    } catch (IOException ex) {
                        Logger.getLogger(ManageOrderRecords.class.getName()).log(Level.SEVERE, null, ex);
                    }
         }
    }//GEN-LAST:event_confrimbActionPerformed

    private void confrimbStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_confrimbStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_confrimbStateChanged

    private void confrimbComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_confrimbComponentHidden
        // TODO add your handling code here:
        confrimb.setEnabled(false);
    }//GEN-LAST:event_confrimbComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageOrderRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageOrderRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageOrderRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageOrderRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageOrderRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SenderID;
    private javax.swing.JTextField StaffIDb;
    private javax.swing.JButton addb;
    private javax.swing.JButton backb;
    private javax.swing.JButton confrimb;
    private javax.swing.JButton deleteb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField orderid;
    private javax.swing.JTextField payments;
    private javax.swing.JTextField receiverName;
    private javax.swing.JTextField receiveraddress;
    private javax.swing.JTextField receiverphone;
    private javax.swing.JButton searchb;
    private javax.swing.JTextField sendername;
    private javax.swing.JButton updateb;
    private javax.swing.JButton viewb;
    private JTextField weight;
}
